FROM ghcr.io/beeman/solana-test-validator:latest
# Clone the Metaplex program from the Solana Devnet cluster
CMD ["solana-test-validator", "--url", "https://api.devnet.solana.com", "--clone", "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"]